### ISSUE TITLE
Scaffold networking struct

### ISSUE THREAD

**Issue by rutgerfarry** [brandonlee503/C7FIT#17]
Create a struct containing all networking calls that will be used by the data store to construct requests. Probably start with just fetching JSON from Github. Consider using [Moya](https://github.com/Moya/Moya) library.

**Resources:**
- http://chris.eidhof.nl/post/typesafe-url-routes-in-swift/
- https://github.com/Moya/Moya

**Comment by brandonlee503** [comment]
Probably not going to use Moya since we aren't using Alamofire. All the data managers are distinct and labeled respectively to their services, eg. - eBayDataManager, FirebaseDataManager
