### ISSUE TITLE
Should we use RxSwift?

### ISSUE THREAD

**Issue by rutgerfarry** [brandonlee503/C7FIT#20]
My basic idea is to just use it as a wrapper over KVO's horrible API. No crazy piping of functions - basically just using RxSwift's [Variables](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/GettingStarted.md#variables).

https://ashfurrow.com/blog/reactivecocoa-vs-rxswift/

**Comment by brandonlee503** [comment]
We've decided to limit our dependencies on external APIs as much as possible. So while Apple's KVO is kinda dated, we're sticking to it for now.
