### ISSUE TITLE
Add fastlane/snapshot to automatically generate app screenshots

### ISSUE THREAD

**Issue by rutgerfarry** [brandonlee503/C7FIT#73]
https://github.com/fastlane/fastlane/tree/master/snapshot

**Comment by brandonlee503** [comment]
Wanna add screenshots/sketch to the readme also? Kinda like [this](https://github.com/classmere/ios/blob/master/README.md).

**Comment by rutgerfarry** [comment]
Yeah! Made that an issue here: #75

**Comment by rutgerfarry** [comment]
closed by #74
